### ISSUE TITLE
Brazil school doesn't appears in the map

### ISSUE THREAD

**Issue by pxalcantara** [DLu/ros_map#118]
Hello @DLu even after your corrections, the Universidade Federal da Bahia university doesn't appears yet,  in the map, could you, please, take a look.

Thanks!!

**Comment by DLu** [comment]
Google caches the data in the Maps API for a bit. If it doesn't appear this week, please reopen this issue. 

https://stackoverflow.com/questions/7930660/google-maps-api-v3-kml-layer-changes
