### ISSUE TITLE
Overlay not displaying anymore?

### ISSUE THREAD

**Issue by mikaelarguedas** [DLu/ros_map#205]
I didnt visit the site for a while, I tried recently on multiple browsers and the ovarlay doesnt display on the map for me
![Screenshot 2022-08-02 05:53:50](https://user-images.githubusercontent.com/6644208/182288409-a5540b6a-da9d-44b9-a303-9b04feeffb53.png)

**Comment by DLu** [comment]
I [fixed the formatting with the Jacobs entry in europe.yaml](https://github.com/DLu/ros_map/commit/ebf6f86f105ac3e589c928b34ae1e53fb632250d). Cache will update soon I presume.

**Comment by DLu** [comment]
Seems to work for me now. @mikaelarguedas Can you confirm?

**Comment by mikaelarguedas** [comment]
It fixed the problem :+1: thanks!
