### ISSUE TITLE
No URL displayed if there is a description

### ISSUE THREAD

**Issue by joshnewans** [DLu/ros_map#219]
It seems that if a description is supplied, the box displays the name and description (no URL even if supplied). If there is no description, it instead shows a table listing the type and URL (and possibly other info if specified?).

I would expect that the URL is meant to still be accessible on entries that also have a description?

P.S. Thanks for such a cool tool!

![image](https://user-images.githubusercontent.com/13210235/193184607-cc874988-fa24-4347-927d-7a3dc2df4715.png)

**Comment by DLu** [comment]
Closed with new infoboxes in #236
